export const commerceToolDefinitions = [
  {
    name: 'search_products',
    description: 'Mencari produk berdasarkan kata kunci.',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } }, required: ['query'] },
    permission: 'commerce_read',
    confirmation: 'none',
    mutation: false,
    idempotent: true,
    timeoutMs: 5000,
  },
  {
    name: 'get_product_details',
    description: 'Melihat detail produk.',
    inputSchema: { type: 'object', properties: { productId: { type: 'string' } }, required: ['productId'] },
    permission: 'commerce_read',
    confirmation: 'none',
    mutation: false,
    idempotent: true,
    timeoutMs: 5000,
  },
  {
    name: 'get_outlets',
    description: 'Mendapatkan daftar outlet yang tersedia.',
    inputSchema: { type: 'object', properties: {} },
    permission: 'commerce_read',
    confirmation: 'none',
    mutation: false,
    idempotent: true,
    timeoutMs: 5000,
  },
  {
    name: 'select_outlet',
    description: 'Memilih outlet untuk pesanan.',
    inputSchema: { type: 'object', properties: { outletId: { type: 'string' } }, required: ['outletId'] },
    permission: 'commerce_write',
    confirmation: 'customer',
    mutation: true,
    idempotent: false,
    timeoutMs: 5000,
  },
  {
    name: 'add_cart_item',
    description: 'Menambahkan produk ke keranjang.',
    inputSchema: { type: 'object', properties: { productId: { type: 'string' }, quantity: { type: 'integer', minimum: 1, description: 'Jumlah produk yang dipesan (wajib)' } }, required: ['productId', 'quantity'] },
    permission: 'commerce_write',
    confirmation: 'customer',
    mutation: true,
    idempotent: false,
    timeoutMs: 5000,
  },
  {
    name: 'get_active_cart',
    description: 'Melihat isi keranjang saat ini.',
    inputSchema: { type: 'object', properties: {} },
    permission: 'commerce_read',
    confirmation: 'none',
    mutation: false,
    idempotent: true,
    timeoutMs: 5000,
  },
  {
    name: 'create_order',
    description: 'Membuat pesanan dari keranjang.',
    inputSchema: { type: 'object', properties: { outletId: { type: 'string' } }, required: ['outletId'] },
    permission: 'commerce_write',
    confirmation: 'customer',
    mutation: true,
    idempotent: false,
    timeoutMs: 10000,
  },
  {
    name: 'get_order_status',
    description: 'Melihat status pesanan.',
    inputSchema: { type: 'object', properties: { orderId: { type: 'string' } }, required: ['orderId'] },
    permission: 'commerce_read',
    confirmation: 'none',
    mutation: false,
    idempotent: true,
    timeoutMs: 5000,
  },
  {
    name: 'get_payment_status',
    description: 'Melihat status pembayaran. READ-ONLY. AI tidak bisa menandai pesanan sebagai dibayar.',
    inputSchema: { type: 'object', properties: { paymentId: { type: 'string' } }, required: ['paymentId'] },
    permission: 'payment_read',
    confirmation: 'none',
    mutation: false,
    idempotent: true,
    timeoutMs: 5000,
  },
  {
    name: 'get_payment_methods',
    description: 'Melihat metode pembayaran yang tersedia.',
    inputSchema: { type: 'object', properties: { outletId: { type: 'string' } }, required: ['outletId'] },
    permission: 'payment_read',
    confirmation: 'none',
    mutation: false,
    idempotent: true,
    timeoutMs: 5000,
  },
  {
    name: 'create_payment_link',
    description: 'Membuat link pembayaran untuk customer. AI tidak bisa menandai sebagai paid.',
    inputSchema: { type: 'object', properties: { orderId: { type: 'string' } }, required: ['orderId'] },
    permission: 'payment_write',
    confirmation: 'customer',
    mutation: true,
    idempotent: true,
    timeoutMs: 10000,
  },
  {
    name: 'report_complaint',
    description: 'Melaporkan keluhan customer.',
    inputSchema: {
      type: 'object',
      properties: {
        orderId: { type: 'string' },
        issue: { type: 'string' },
        priority: { type: 'string', enum: ['low', 'medium', 'high'] },
      },
      required: ['issue'],
    },
    permission: 'support_write',
    confirmation: 'customer',
    mutation: true,
    idempotent: false,
    timeoutMs: 5000,
  },
  {
    name: 'find_nearest_outlet',
    description: 'Mencari outlet SelaluTeh terdekat dari lokasi customer. Input bisa nama jalan, nama daerah, landmark, atau koordinat yang dibagikan.',
    inputSchema: {
      type: 'object',
      properties: {
        text: { type: 'string', description: 'Nama jalan, daerah, landmark, atau mall (contoh: Jalan Biawan Samarinda, Air Putih Samarinda, Big Mall Samarinda)' },
        latitude: { type: 'number', description: 'Koordinat latitude jika dibagikan' },
        longitude: { type: 'number', description: 'Koordinat longitude jika dibagikan' },
      },
    },
    permission: 'commerce_read',
    confirmation: 'none',
    mutation: false,
    idempotent: true,
    timeoutMs: 10000,
  },
  {
    name: 'handover_to_human',
    description: 'Mengalihkan percakapan ke admin/manusia.',
    inputSchema: { type: 'object', properties: { reason: { type: 'string' } }, required: ['reason'] },
    permission: 'support_write',
    confirmation: 'none',
    mutation: true,
    idempotent: false,
    timeoutMs: 5000,
  },
];

export const FORBIDDEN_TOOLS = new Set(['mark_payment_paid', 'mark_order_paid', 'set_payment_status']);
