export const ConnectionStatus = {
  NOT_CONNECTED: 'NOT_CONNECTED',
  PENDING_SETUP: 'PENDING_SETUP',
  CONNECTED: 'CONNECTED',
  NEEDS_REAUTHORIZATION: 'NEEDS_REAUTHORIZATION',
  DEGRADED: 'DEGRADED',
  DISCONNECTED: 'DISCONNECTED',
  ERROR: 'ERROR',
};

export const ChannelType = {
  WHATSAPP: 'WHATSAPP',
  TELEGRAM: 'TELEGRAM',
  INSTAGRAM: 'INSTAGRAM',
};

export const CHANNEL_ERRORS = {
  NOT_FOUND: { code: 'CHANNEL_CONNECTION_NOT_FOUND', status: 404 },
  NOT_CONNECTED: { code: 'CHANNEL_NOT_CONNECTED', status: 400 },
  WEBHOOK_VERIFICATION_FAILED: { code: 'CHANNEL_WEBHOOK_VERIFICATION_FAILED', status: 401 },
  OUTLET_DISABLED: { code: 'CHANNEL_OUTLET_DISABLED', status: 400 },
};
