export const PUBLIC_ORDER_STATUS = {
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAID: 'PAID',
  AWAITING_OUTLET_APPROVAL: 'AWAITING_OUTLET_APPROVAL',
  PREPARING: 'PREPARING',
  READY_FOR_PICKUP: 'READY_FOR_PICKUP',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  PAYMENT_EXPIRED: 'PAYMENT_EXPIRED',
}

export const PUBLIC_ORDER_STATUS_LABELS = {
  PAYMENT_PENDING: 'Menunggu Pembayaran',
  PAID: 'Dibayar',
  AWAITING_OUTLET_APPROVAL: 'Diproses Outlet',
  PREPARING: 'Sedang Dibuat',
  READY_FOR_PICKUP: 'Siap Diambil',
  COMPLETED: 'Selesai',
  CANCELLED: 'Dibatalkan',
  PAYMENT_EXPIRED: 'Pembayaran Kedaluwarsa',
}
